# Generated by Django 2.2.10 on 2020-09-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основной раздел')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=50, verbose_name='Раздел')),
                ('title', models.ManyToManyField(through='articles.Relationship', to='articles.Article')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделов',
            },
        ),
        migrations.AddField(
            model_name='relationship',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Sections'),
        ),
    ]
