# Generated by Django 2.2.10 on 2020-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('image', models.TextField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
    ]
