# Generated by Django 2.2.10 on 2020-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='extra',
            field=models.CharField(max_length=200, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='duble_camera',
            field=models.BooleanField(null=True, verbose_name='Двойная камера'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='fm',
            field=models.BooleanField(null=True, verbose_name='FM-радио'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='os',
            field=models.CharField(max_length=50, verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='pixel',
            field=models.IntegerField(verbose_name='Число пикселей на дюйм'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='processor',
            field=models.CharField(max_length=50, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ram',
            field=models.IntegerField(verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen',
            field=models.CharField(max_length=50, verbose_name='Разрешение экрана'),
        ),
        migrations.AlterField(
            model_name='sumsung',
            name='extra',
            field=models.CharField(max_length=200, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='xiomi',
            name='extra',
            field=models.CharField(max_length=200, verbose_name='Дополнительно'),
        ),
    ]
