# Generated by Django 2.2.10 on 2020-09-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20200904_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iphone',
            old_name='model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sumsung',
            old_name='model',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='xiomi',
            old_name='model',
            new_name='name',
        ),
    ]
